### ISSUE TITLE
 spill_removal + gloopblocks mods

### ISSUE THREAD

**Issue by waxtatect** [banananaland/bananaland-mods#300]
https://github.com/pandorabox-io/spill_removal/blob/1e0285ac48f7908942a89377786b88813722e356/cooling.lua#L3

https://github.com/mt-mods/gloopblocks/blob/9a4b6e7900d40b91f30217b1d1da454f33b28243/lava-handling.lua#L52

if spill_removal (hmm) mod loads first, then this wont work
https://github.com/pandorabox-io/spill_removal/blob/1e0285ac48f7908942a89377786b88813722e356/commands.lua#L2

**Comment by BuckarooBanzay** [comment]
afaik, if `gloopblocks_lavacooling` is not set this wont even register: https://github.com/mt-mods/gloopblocks/blob/9a4b6e7900d40b91f30217b1d1da454f33b28243/lava-handling.lua#L6

**Comment by BuckarooBanzay** [comment]
@waxtatect ping ^ (please correct me if i'm wrong)

**Comment by waxtatect** [comment]
"if minetest.setting_getbool("gloopblocks_lavacooling") ~= false then"
this condition is met by default, so yes this is registered

**Comment by BuckarooBanzay** [comment]
>  this condition is met by default, so yes this is registered

my bad, somehow i thought it would never enter the function :facepalm: anyway: i don't think this mod is even relevant now that i looked at the gloopblocks cooling method :shrug: 

also: :ninja:
